{ lib
, fetchFromGitHub
, python27
}:
with python27.pkgs;
buildPythonApplication rec {

  pname = "svtyper";
  version = "0.7.1";

  src = fetchFromGitHub {
    owner = "hall-lab";
    repo = pname;
    rev = "v${version}";
    sha256 = "1rhllbs4kldq8g3hm1qvz1dbqn7fdavqjsm0290yxdjd3kmkxbmp";
  };

  prePatch = ''
    substituteInPlace ./setup.py \
      --replace "tests_require=['pytest==4.6.4']," "tests_require=['pytest>=4.6.4'],"
  '';

  checkInputs = [ pytest pytestrunner ];

  propagatedBuildInputs = [ numpy pysam scipy cytoolz ];

  meta = with lib; {
    homepage = "https://github.com/hall-lab/svtyper";
    description = "genotyping of structural variants";
    license = licenses.gpl3;
    longDescription = ''
      SVTyper performs breakpoint genotyping of structural variants
      (SVs) using whole genome sequencing data.
      Users must supply a VCF file of sites to genotype
      (which may be generated by LUMPY) as well as a BAM/CRAM
      file of Illumina paired-end reads aligned with BWA-MEM.
      SVTyper assesses discordant and concordant reads
      from paired-end and split-read alignments to infer genotypes
      at each site. Algorithm details and benchmarking are described
      in Chiang et al., 2015
    '';
    maintainers = with maintainers; [ scalavision ];
  };

}
